name: onlineshop_77
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  intl: ^0.18.1
  image_picker: ^1.0.4
  easy_localization: ^3.0.3
  shared_preferences: ^2.2.1
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  shimmer: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  equatable: ^2.0.5
  mask_text_input_formatter: ^2.5.0
  formz: ^0.6.1
  get_it: ^7.6.4
  reorderable_grid_view: ^2.2.7
  dotted_border: ^2.1.0
  url_launcher: ^6.1.14
  screenshot: ^2.1.0
  path_provider: ^2.1.1
  image_gallery_saver: ^2.0.3
  yandex_mapkit: ^3.3.3
  dropdown_button2: ^2.3.9
  highlight_text: ^1.7.0
  dio: ^5.3.3
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/fonts/
    - assets/translations/
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
